# Global Cost Optimization and Sustainability Configuration

# This configuration file defines strategies and measures for optimizing costs
# and ensuring sustainability across infrastructure deployments in the Symbiotic Syntheconomy project.

---
# General Configuration
version: '1.0.0'
name: 'Global Cost Optimization and Sustainability'
description: 'Configuration for long-term infrastructure viability through cost optimization and sustainable practices'

# Cost Optimization Strategies
costOptimization:
  # Resource Scaling
  autoScaling:
    enabled: true
    metrics:
      - cpuUtilization:
          target: 70
          minInstances: 1
          maxInstances: 10
      - memoryUtilization:
          target: 80
          minInstances: 1
          maxInstances: 10
  # Reserved Instances and Savings Plans
  reservedResources:
    enabled: true
    commitmentPeriod: '1y'
    services:
      - compute
      - storage
    discountThreshold: 20  # Percentage savings required to opt for reserved resources
  # Spot Instances for non-critical workloads
  spotInstances:
    enabled: true
    workloadTypes:
      - batchProcessing
      - testing
    maxBidMultiplier: 1.5  # Maximum bid as a multiplier of on-demand price

# Sustainability Measures
sustainability:
  # Energy Efficiency
  energyEfficiency:
    enabled: true
    preferredRegions:
      - region: 'us-west-2'
        reason: 'High renewable energy usage'
      - region: 'eu-north-1'
        reason: 'Carbon-neutral data centers'
    powerUsageEffectiveness:
      targetPUE: 1.2  # Target Power Usage Effectiveness ratio
  # Carbon Footprint Reduction
  carbonOffset:
    enabled: true
    offsetPrograms:
      - program: 'Reforestation Initiative'
        contribution: 10  # Percentage of carbon emissions to offset
      - program: 'Renewable Energy Credits'
        contribution: 15
  # Resource Recycling
  resourceRecycling:
    enabled: true
    policies:
      - recycleUnusedAMIs: true
      - deleteUnusedSnapshots: true
        retentionDays: 30

# Monitoring and Alerts
monitoring:
  costAlerts:
    enabled: true
    thresholds:
      - budgetLimit: 10000  # Monthly budget limit in USD
        alertPercentage: 80  # Alert when 80% of budget is reached
      - spikeDetection:
          enabled: true
          increaseThreshold: 30  # Alert on 30% cost increase day-over-day
  sustainabilityMetrics:
    enabled: true
    metrics:
      - carbonFootprint
      - energyConsumption
    reportingFrequency: 'weekly'

# Automation and Optimization Scripts
automation:
  costOptimizationScripts:
    - script: 'optimize-instances.js'
      schedule: 'daily'
      description: 'Script to shutdown idle instances and optimize resource allocation'
  sustainabilityScripts:
    - script: 'carbon-footprint-report.js'
      schedule: 'monthly'
      description: 'Generate and distribute carbon footprint reports'

# Compliance and Governance
compliance:
  costPolicies:
    enforceTagging: true
    mandatoryTags:
      - 'Environment'
      - 'Project'
      - 'Owner'
  sustainabilityPolicies:
    greenCertification: true
    auditFrequency: 'quarterly'
